### ISSUE TITLE
Feature #1: User can view the list of shows

### ISSUE THREAD

**Issue by jeremyhnguyen** [jeremyhnguyen/AniMid#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the list of shows

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User should be able to see carousel of select few popular shows & a tiled list of other shows

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

DESKTOP
![Screenshot 2023-09-29 at 3 19 44 PM](https://github.com/jeremyhnguyen/ajax-project/assets/136545701/72f1c942-f404-48ee-ba5e-b278daba996c)
MOBILE
![Screenshot 2023-09-29 at 3 22 16 PM](https://github.com/jeremyhnguyen/ajax-project/assets/136545701/15f5750d-22c6-4670-a86b-fb3749e83b20)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Complete HTML structure for the main page (should be mobile and desktop responsive)
    - [x] add navbar that follows screen on scroll (<a> logo/name, menu button w/ select)
    - [x] add carousel that cycles a few images (chevrons, radios)
    - [x] create tiles in 5 columns
- [x] Complete Basic CSS styling for the main page (structure, colors, fonts)
    - [x] apply dark mode scheme
    - [x] add font family
    - [x] style rows/columns
    - [x] style tiles 
    - [x] adjust media queries for screen sizes
- [x] add some basic navbar functionality
    - [x] menu select should show options for airing/popular/upcoming/random
    - [x] logo/name should take user back to home screen 
- [x] tiles
    - [x] round off tile edges sightly
    - [x] make images display on tiles for each show
    - [x] make descriptions display under show image
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
