### ISSUE TITLE
Feature #2: User can filter shows 

### ISSUE THREAD

**Issue by jeremyhnguyen** [jeremyhnguyen/AniMid#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can filter the list of shows

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can filter shows using the menu to show popular/upcoming shows

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

DESKTOP
![Screenshot 2023-09-29 at 3 43 01 PM](https://github.com/jeremyhnguyen/ajax-project/assets/136545701/7db066f1-5c0a-4f9d-9e15-f0a428b23e6c)
MOBILE
![Screenshot 2023-09-29 at 3 43 11 PM](https://github.com/jeremyhnguyen/ajax-project/assets/136545701/52002255-119e-4e68-9e49-82b394faf48c)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make menu functional
    - [x] select inputs should viewswap to each different view (airing/popular/upcoming)
    - [x] each page should be a new display array of it's respective category
    - [x] make sure all pages return to proper screen
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
