### ISSUE TITLE
Feature #3: User can view details of selected show 

### ISSUE THREAD

**Issue by jeremyhnguyen** [jeremyhnguyen/AniMid#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a show

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can select a show and it should show the image, synopsis and a preview

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

DESKTOP
![Screenshot 2023-09-29 at 4 12 39 PM](https://github.com/jeremyhnguyen/ajax-project/assets/136545701/55adde75-3cbf-4aa3-afff-9363ba442339)

MOBILE
![Screenshot 2023-09-29 at 4 12 57 PM](https://github.com/jeremyhnguyen/ajax-project/assets/136545701/05a8d353-6533-43e0-8144-f02fab5a4ec8)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create html/css for individual page view
- [x] create dummy domtree for testing page
- [x] function to render the domtree for individual page view
- [x] write function to use data-id (mal_id) to get each individual show
   - [x] each show's view should have image, synopsis & other show info, and a preview video
   - [x] viewswap should work properly when going between other views 
   - [x] delete dummy testing elements
- [x] fix css to make image tiles uniform
- [x] fix logo stretching on mobile view 
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
