### ISSUE TITLE
Feature #4: User can view a random show 

### ISSUE THREAD

**Issue by jeremyhnguyen** [jeremyhnguyen/AniMid#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a random show from the available selection

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click random to view a random show

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

DESKTOP
![Screenshot 2023-09-29 at 4 16 56 PM](https://github.com/jeremyhnguyen/ajax-project/assets/136545701/2d590b83-ea53-4bfb-b115-f52d52e400bc)

MOBILE
![Screenshot 2023-09-29 at 4 17 05 PM](https://github.com/jeremyhnguyen/ajax-project/assets/136545701/d6b5a23c-0bb0-4452-b335-b17346924c5b)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] make random input functional (menu or standalone button)
- [ ] add video preview to individual view
- [ ] event listener to load API(random) information into individual view
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
